import QuickNotes from '@/components/quick-notes';
import { translations } from '@/lib/translations';
import { act,cleanup,fireEvent,render,screen } from '@testing-library/react';
import { afterEach,expect,it,vi } from 'vitest';
vi.mock('@/components/latex-toolbar', () => ({ LatexQuickToolbar: () => null }));
vi.mock('@/components/ui-text', () => ({ UiText: () => null }));
afterEach(cleanup);
it('keeps a dirty draft across snapshots and failed writes, closing only after success', async () => {
  let finish!: (success: boolean) => void;
  const save = vi.fn(() => new Promise<boolean>(resolve => { finish = resolve; }));
  const props = { t: translations.en, lang: 'en', onNotesChange: save };
  const view = render(<QuickNotes {...props} notes="original" />);
  fireEvent.click(screen.getByRole('button', { name: translations.en.personalNotes }));
  const input = screen.getByPlaceholderText(translations.en.notesPlaceholder) as HTMLTextAreaElement;
  fireEvent.change(input, { target: { value: 'unsaved draft' } });
  view.rerender(<QuickNotes {...props} notes="late remote snapshot" />);
  expect(input.value).toBe('unsaved draft');
  fireEvent.click(screen.getByRole('button', { name: translations.en.save }));
  expect(save).toHaveBeenCalledWith('unsaved draft');
  expect(input.disabled).toBe(true);
  expect(screen.getByRole('dialog')).toBeTruthy();
  await act(async () => finish(false));
  expect(input.value).toBe('unsaved draft');
  expect(input.disabled).toBe(false);
  fireEvent.click(screen.getByRole('button', { name: translations.en.save }));
  await act(async () => finish(true));
  expect(screen.queryByRole('dialog')).toBeNull();
});
